/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.figurasgeometricas;

/**
 *
 * @author pipet
 */
public class VentanaPpal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPpal
     */
    public VentanaPpal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BtnTriangulo = new javax.swing.JButton();
        BtnCirculo = new javax.swing.JButton();
        BtnCuadrado = new javax.swing.JButton();
        BtnRectangulo = new javax.swing.JButton();
        BtnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("¿Cual es tu figura geometrica?");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(120, 40, 280, 24);

        BtnTriangulo.setBackground(new java.awt.Color(255, 204, 0));
        BtnTriangulo.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        BtnTriangulo.setForeground(new java.awt.Color(204, 255, 102));
        BtnTriangulo.setText("Triangulo Rectangulo");
        BtnTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTrianguloActionPerformed(evt);
            }
        });
        jPanel1.add(BtnTriangulo);
        BtnTriangulo.setBounds(270, 100, 180, 90);

        BtnCirculo.setBackground(new java.awt.Color(204, 0, 0));
        BtnCirculo.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        BtnCirculo.setForeground(new java.awt.Color(255, 102, 102));
        BtnCirculo.setText("Círculo");
        BtnCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCirculoActionPerformed(evt);
            }
        });
        jPanel1.add(BtnCirculo);
        BtnCirculo.setBounds(270, 220, 180, 90);

        BtnCuadrado.setBackground(new java.awt.Color(0, 153, 153));
        BtnCuadrado.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        BtnCuadrado.setForeground(new java.awt.Color(153, 255, 204));
        BtnCuadrado.setText("Cuadrado");
        BtnCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCuadradoActionPerformed(evt);
            }
        });
        jPanel1.add(BtnCuadrado);
        BtnCuadrado.setBounds(60, 220, 170, 90);

        BtnRectangulo.setBackground(new java.awt.Color(0, 153, 0));
        BtnRectangulo.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        BtnRectangulo.setForeground(new java.awt.Color(102, 255, 102));
        BtnRectangulo.setText("Rectangulo");
        BtnRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRectanguloActionPerformed(evt);
            }
        });
        jPanel1.add(BtnRectangulo);
        BtnRectangulo.setBounds(60, 100, 170, 90);

        BtnSalir.setText("Salir");
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(BtnSalir);
        BtnSalir.setBounds(410, 10, 100, 24);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTrianguloActionPerformed
        // TODO add your handling code here:
        Vtriangulo ventanat = new Vtriangulo();
        ventanat.setVisible(true);
        
    }//GEN-LAST:event_BtnTrianguloActionPerformed

    private void BtnCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCirculoActionPerformed
        // TODO add your handling code here:
        Vcirculo ventanac = new Vcirculo();
        ventanac.setVisible(true);
    }//GEN-LAST:event_BtnCirculoActionPerformed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_BtnSalirActionPerformed

    private void BtnCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCuadradoActionPerformed
        // TODO add your handling code here:
        Vcuadrado ventanacu = new Vcuadrado();
        ventanacu.setVisible(true);
    }//GEN-LAST:event_BtnCuadradoActionPerformed

    private void BtnRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRectanguloActionPerformed
        // TODO add your handling code here:
        Vrectangulo ventanar = new Vrectangulo();
        ventanar.setVisible(true);
    }//GEN-LAST:event_BtnRectanguloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPpal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCirculo;
    private javax.swing.JButton BtnCuadrado;
    private javax.swing.JButton BtnRectangulo;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JButton BtnTriangulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
