/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ex_18;

/**
 *
 * @author pipet
 */
public class VentanaPpal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPpal
     */
    public VentanaPpal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TxtCodigo = new javax.swing.JTextField();
        TxtNombre = new javax.swing.JTextField();
        TxtHorasT = new javax.swing.JTextField();
        TxtValorHora = new javax.swing.JTextField();
        TxtRetencion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TxtSb = new javax.swing.JTextField();
        TxtSn = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        BtnGenerar = new javax.swing.JButton();
        BtnBorrar = new javax.swing.JButton();
        BtnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 255, 204));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setLayout(null);

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Código");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 40, 60, 16);

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 80, 80, 16);

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Horas trabajadas");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 120, 110, 16);

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Valor x hora");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(290, 40, 90, 16);

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Retención");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(290, 80, 70, 16);
        jPanel1.add(TxtCodigo);
        TxtCodigo.setBounds(130, 40, 130, 24);
        jPanel1.add(TxtNombre);
        TxtNombre.setBounds(130, 80, 130, 24);
        jPanel1.add(TxtHorasT);
        TxtHorasT.setBounds(130, 120, 130, 24);
        jPanel1.add(TxtValorHora);
        TxtValorHora.setBounds(390, 40, 130, 24);
        jPanel1.add(TxtRetencion);
        TxtRetencion.setBounds(390, 80, 130, 24);

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Salario bruto");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 240, 80, 16);

        TxtSb.setEditable(false);
        TxtSb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSbActionPerformed(evt);
            }
        });
        jPanel1.add(TxtSb);
        TxtSb.setBounds(130, 240, 130, 24);

        TxtSn.setEditable(false);
        jPanel1.add(TxtSn);
        TxtSn.setBounds(360, 240, 130, 24);

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Salario neto");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(280, 240, 80, 16);

        BtnGenerar.setText("Generar salario");
        BtnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGenerarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnGenerar);
        BtnGenerar.setBounds(250, 180, 100, 24);

        BtnBorrar.setText("Borrar");
        BtnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBorrarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnBorrar);
        BtnBorrar.setBounds(140, 300, 80, 24);

        BtnSalir.setText("Salir");
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(BtnSalir);
        BtnSalir.setBounds(380, 300, 90, 24);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtSbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSbActionPerformed

    private void BtnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGenerarActionPerformed
        // TODO add your handling code here:
        double Ht, Vh, R, SB, SN;
        Ht = Double.parseDouble(TxtHorasT.getText());
        Vh = Double.parseDouble(TxtValorHora.getText());
        R = Double.parseDouble(TxtRetencion.getText());
        
        Salarios trabajador = new Salarios(Ht,Vh,R);
        
        SB = trabajador.SalarioBruto();
        SN = trabajador.SalarioNeto();
        
        TxtSb.setText(String.valueOf(SB));
        TxtSn.setText(String.valueOf(SN));
        
        
    }//GEN-LAST:event_BtnGenerarActionPerformed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_BtnSalirActionPerformed

    private void BtnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBorrarActionPerformed
        // TODO add your handling code here:
        TxtCodigo.setText("");
        TxtNombre.setText("");
        TxtHorasT.setText("");
        TxtValorHora.setText("");
        TxtRetencion.setText("");
        TxtSb.setText("");
        TxtSn.setText("");
        
    }//GEN-LAST:event_BtnBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPpal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBorrar;
    private javax.swing.JButton BtnGenerar;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JTextField TxtCodigo;
    private javax.swing.JTextField TxtHorasT;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JTextField TxtRetencion;
    private javax.swing.JTextField TxtSb;
    private javax.swing.JTextField TxtSn;
    private javax.swing.JTextField TxtValorHora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
