/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ex_22;

/**
 *
 * @author pipet
 */
public class VentanaPpal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPpal
     */
    public VentanaPpal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        txtHorasT = new javax.swing.JTextField();
        BtnGenerar = new javax.swing.JButton();
        txtRn = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtRs = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        BtnBorrar = new javax.swing.JButton();
        BtnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(null);

        jLabel1.setText("Nombre:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 30, 60, 16);

        jLabel2.setText("Valor x Hora");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 70, 90, 16);

        jLabel3.setText("Horas trabajadas:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 110, 110, 16);

        jLabel4.setText("Resultado");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 200, 70, 20);

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombre);
        txtNombre.setBounds(160, 30, 110, 24);
        jPanel1.add(txtValor);
        txtValor.setBounds(160, 70, 110, 24);
        jPanel1.add(txtHorasT);
        txtHorasT.setBounds(160, 110, 110, 24);

        BtnGenerar.setText("Generar");
        BtnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGenerarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnGenerar);
        BtnGenerar.setBounds(160, 160, 120, 24);

        txtRn.setEditable(false);
        txtRn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRnActionPerformed(evt);
            }
        });
        jPanel1.add(txtRn);
        txtRn.setBounds(120, 200, 110, 24);

        jLabel5.setText("Nombre");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(150, 240, 50, 16);

        txtRs.setEditable(false);
        jPanel1.add(txtRs);
        txtRs.setBounds(270, 200, 130, 24);

        jLabel6.setText("Sueldo");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(320, 240, 39, 16);

        BtnBorrar.setText("Borrar");
        BtnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBorrarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnBorrar);
        BtnBorrar.setBounds(70, 290, 90, 24);

        BtnSalir.setText("Salir");
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(BtnSalir);
        BtnSalir.setBounds(270, 290, 110, 24);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGenerarActionPerformed
        // TODO add your handling code here:
        double V, H;
        String N, S;
        N = txtNombre.getText();
        V = Double.parseDouble(txtValor.getText());
        H = Double.parseDouble(txtHorasT.getText());
        
        Salario trabajador = new Salario(H,V);
        
        S = trabajador.generar();
        
        txtRn.setText(N);
        txtRs.setText(S);
    }//GEN-LAST:event_BtnGenerarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtRnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRnActionPerformed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_BtnSalirActionPerformed

    private void BtnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBorrarActionPerformed
        // TODO add your handling code here:
        txtNombre.setText("");
        txtValor.setText("");
        txtHorasT.setText("");
        txtRn.setText("");
        txtRs.setText("");
    }//GEN-LAST:event_BtnBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPpal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBorrar;
    private javax.swing.JButton BtnGenerar;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtHorasT;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRn;
    private javax.swing.JTextField txtRs;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
